config/routes.rb
Rails.application.routes.draw do

  root "home#index"

  devise_scope :user do
    authenticated :user do
      root 'ideas#index', as: :authenticated_root
    end

    unauthenticated do
      root 'home#index', as: :unauthenticated_root
    end
  end

  #get '/about', to: 'home#about'
  
  resources :ideas  do 
    member do
      put "like", to: "ideas#upvote"
    end
  end
  
  resources :companies, except: [:index]
  devise_for :users
  resources :users, only: [:index, :show]
  resources :comments, only: [:create, :destroy, :show]

end

app/models/idea.rb
class Idea < ActiveRecord::Base
  belongs_to :user
  acts_as_commentable
  acts_as_votable
  mount_uploader :attachment, AttachmentUploader

  scope :top_5, -> { order(:cached_votes_score).reverse.take(5) }

  def votes_for_pie_chart
    {
      'no' => number_of_people_in_company - number_of_votes,
      'yes' => number_of_votes
    }  
  end

  def number_of_votes
    get_upvotes.count
  end

  def number_of_people_in_company
    user.company.users.count
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  load_and_authorize_resource

  # GET /ideas
  # GET /ideas.json
  def index
    @top_5_ideas = Idea.top_5
    @ideas = Idea.all
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
  end

  def upvote 
    authorize! :upvote, Idea
    @idea.upvote_by current_user
    redirect_to :back
  end  

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = current_user.ideas.new(idea_params)
    # @idea = Idea.new(idea_params)

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:title, :user_id, :blurb, :reason, :goal, :implementation, :budget, :attachment)
    end
  end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/ideas/_form.html.erb
<h1><%= current_user.name %> proposes a new idea</h1>

<%= form_for(@idea) do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<section>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :blurb %><br>
    <%= f.text_area :blurb %>
  </div>
  <div class="field">
    <%= f.label :reason %><br>
    <%= f.text_area :reason %>
  </div>
  <div class="field">
    <%= f.label :goal %><br>
    <%= f.text_area :goal %>
  </div>
  <div class="field">
    <%= f.label :implementation %><br>
    <%= f.text_area :implementation %>
  </div>
  <div class="field">
    <%= f.label :budget %><br>
    <%= f.text_field :budget %>
  </div>
  <div class="field">
     <%= f.label :attachment %><br />
     <%= f.file_field :attachment %>
   </div>

  <div class="actions">
    <%= f.submit class: "button" %>
  </div>
<% end %>
</section>

app/views/ideas/_idea.html.erb
<li>
<ul>
  <% if current_user.company.id == idea.user.company.try(:id) %>
  <li><%= link_to idea.user do %></li>
  <br>
    <%= image_tag idea.user.try(:image_url) %>
    <% end %>
  <li><%= link_to idea.title, idea %></li>
  <li>By <%= link_to idea.user.name, idea.user %></li>
  <% end %>
  </ul>
</li>

app/views/ideas/edit.html.erb
<h1>Editing Idea</h1>

<%= render 'form' %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<h1>Top 5 Ideas at <%= link_to current_user.company.try(:name) %></h1>
<div class="top5Grid">
  <ul class="small-block-grid-1 -block-grid-5 large-block-grid-5 showIdeas1">
    <%= render @top_5_ideas %>
  </ul>
</div>

<h1>All ideas at <%= link_to current_user.company.try(:name) %></h1>

<div>
  <ul class="small-block-grid-1 -block-grid-5 large-block-grid-5 showIdeas2">
    <%= render @ideas %>
  </ul>
</div>

app/views/ideas/new.html.erb
<%= render 'form' %>

app/views/ideas/show.html.erb
<div class="showHTMLIdeas">

<p id="titleShowHTMLIdeas">
  <%= @idea.title %>
</p>

<p id="nameShowHTMLIdeas">
  <strong>By </strong>
  <%= @idea.user.name %>
</p>

<p class="fieldsShowHTMLIdeas">
  <strong>Blurb:</strong>
  <%= @idea.blurb %>
</p>

<div id="pieStyle">
<p id="pieStyletxt">Support for <%= @idea.title %></p>
<%= pie_chart @idea.votes_for_pie_chart, class: "float" %>
<%= link_to like_idea_path(@idea), method: :put do %>
  <button>Vote |  
  <%= @idea.get_upvotes.size %></button>
<% end %>
</div>

<p class="fieldsShowHTMLIdeas">
  <strong>Reason:</strong>
  <%= @idea.reason %>
</p>

<p class="fieldsShowHTMLIdeas">
  <strong>Goal:</strong>
  <%= @idea.goal %>
</p>

<p class="fieldsShowHTMLIdeas">
  <strong>Implementation:</strong>
  <%= @idea.implementation %>
</p>

<p class="fieldsShowHTMLIdeas">
  <strong>Budget:</strong>
  <%= @idea.budget %>
</p>

<p class="fieldsShowHTMLIdeas">
  <b>Find out more:</b>
  <%=  link_to "Learn More", @idea.attachment.url %>
</p>

<div>

<%= render partial: 'comments/form', locals: { commentable: @idea } %>
<%= render partial: 'comments/comment', collection: @idea.comments, locals: { commentable: @idea } %>

<% if @idea.user_id == current_user.id %>
<%= link_to 'Edit', edit_idea_path(@idea) %> 
<%= link_to 'Delete', @idea, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>