config/routes.rb
Rails.application.routes.draw do

  root "home#index"

  devise_scope :user do
    authenticated :user do
      root 'ideas#index', as: :authenticated_root
    end

    unauthenticated do
      root 'home#index', as: :unauthenticated_root
    end
  end

  #get '/about', to: 'home#about'
  
  resources :ideas  do 
    member do
      put "like", to: "ideas#upvote"
    end
  end
  
  resources :companies, except: [:index]
  devise_for :users
  resources :users, only: [:index, :show]
  resources :comments, only: [:create, :destroy, :show]

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope -> { order('created_at ASC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_commentable
  
  def create
    @comment = @commentable.comments.build(comments_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @commentable, notice: "Thanks for commenting." }
      else
        format.html { redirect_to @commentable, notice: "Comment wasn't successfully created." }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.html {redirect_to @commentable, notice: "Your comment was successfully destroyed."}
      format.json { head :no_content }
    end
  end
  
  protected
    def set_commentable
      @commentable = params[:commentable_type].camelize.constantize.find(params[:commentable_id])
    end

    def comments_params
      params.require(:comment).permit(:title, :comment)
    end
end

app/views/comments/_comment.html.erb
  <div class="marginCommentsBox">
  <ul>
    <strong><%= comment.user.try(:name) %></strong>
    <%= comment.title %>
    <%= comment.comment %>
    <%= link_to 'Delete Comment', comment_path(comment, commentable_type: commentable.class.to_s.underscore, commentable_id: commentable.id), method: :delete, data: { confirm: 'Are you sure?' } %>
  </ul>
  </div>

app/views/comments/_form.html.erb
<%= form_for(:comment, url: comments_path(commentable_type: commentable.class.to_s.underscore, commentable_id: commentable.id)) do |f| %>

  <%= f.text_area :comment, placeholder: "Discuss the Idea" %>
  <%= f.submit "Contribute", class: "button expand" %>

<% end %>