config/routes.rb
Rails.application.routes.draw do

  root "home#index"

  devise_scope :user do
    authenticated :user do
      root 'ideas#index', as: :authenticated_root
    end

    unauthenticated do
      root 'home#index', as: :unauthenticated_root
    end
  end

  #get '/about', to: 'home#about'
  
  resources :ideas  do 
    member do
      put "like", to: "ideas#upvote"
    end
  end
  
  resources :companies, except: [:index]
  devise_for :users
  resources :users, only: [:index, :show]
  resources :comments, only: [:create, :destroy, :show]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
   <%= favicon_link_tag 'favicon.ico' %>
   <link href='https://fonts.googleapis.com/css?family=Quicksand' rel='stylesheet' type='text/css'>
   
   <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <title><%= content_for?(:title) ? yield(:title) : "bulb" %></title>

  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>
  <header>
    <nav class="top-bar row" data-topbar role="navigation">
      <ul class="title-area">
          <li><img id="logo" src="<%= asset_path( 'bulb-white.png' ) %>">
          <h1><a><%= link_to "bulb", root_path %></a></h1><li>
        <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
        <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
      </ul>

      <section class="top-bar-section">
        <!-- Right Nav Section -->
        <ul class="right">
          <% if current_user %>
          <li><%= link_to "Ideas", ideas_path, class:"active" %></li>
          <li><%= link_to "Propose a New Idea", new_idea_path, class:"active" %></li>
          <li class="has-dropdown">
            <a href="#"><%= current_user.name %></a>
            <ul class="dropdown">
              <li><%= link_to "My Profile", current_user, class:"active" %></li>
              <li><%= link_to "Edit Profile", edit_user_registration_path, class:"active" %></li>
              <li><%= link_to "My Company", users_path, class:"active"%></li> 
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete, class:"active" %></li>
              <% else %>
              <li><%= link_to "Register", new_user_registration_path, class:"active" %></li>
              <li><%= link_to "Login", new_user_session_path, class:"active" %></li>
              <% end %>
            </ul>
          </li>
        </ul>
      </section>
    </nav>
  </header>

  <% flash.each do |name, message| %>
    <div class="flash-message flash-message-<%= name %>">
      <%= message %>
    </div>
  <% end %>

  <main class="row">
    <%= yield %>
  </main>

  <footer>
    <h3>Get in touch</h3>
    <a href="https://uk.linkedin.com/in/psbadewal">
     <img class= "footerimg" src="<%= asset_path( 'noun_111967_cc.png' ) %>"></a>

    <a href="https://twitter.com/psbadewal">
    <img class= "footerimg" src="<%= asset_path( 'noun_26920.png' ) %>"></a>
  </footer>
</body>
</html>